# cassandra-rackdc.properties – Nodos del datacenter CPD2 (PRODUCCIÓN)
# Copiar a: /etc/dse/cassandra/cassandra-rackdc.properties  (instalación por paquete)
#       o:  <install>/resources/cassandra/conf/cassandra-rackdc.properties
#
# Este fichero es IDÉNTICO en los 2 nodos de CPD2.
# Los nodos de CPD1 usan rackdc_CPD1.properties (dc=CPD1).

dc=CPD2
rack=rack1

prefer_local=true
